# .streamlit/secrets.toml
OPENAI_API_KEY = "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"
ASSISTANT_ID   = "asst_hakbmVSNcGcBUTpLp9UXvZS2"
